### ISSUE TITLE
pengecekan dan persiapan bahan

### ISSUE THREAD

**Issue by FaridBayu** [FaridBayu/Projek-akhir#10]
- pengecekan bahan untuk kado

**Comment by Ekiriswann** [comment]
PENGECEKAN DAN PERSIAPAN BARANG
Alat yang di perlukan untuk pembuatan project kado tersebut :
1. Gunting
2. Penggaris
3. Kater 
4. Double Tip
5. Pensil


![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/3e7eb069-af69-4469-a57f-165def2df4f2)



Adapun untuk bahan bahan nya adalah : 
1.	Kertas Karton
 



![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/b5656482-fbd1-4393-bffd-4f582ca00104)




2.	Kertas Kado
  

![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/9086be14-caff-4628-aa32-74421d8a8f88)



3.	Pita 
   



![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/ddfc0977-efc9-4fed-ba56-c0f963d2b694)





4.	Kertas Origami 
  





![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/14a6f8d7-910b-48d1-bedf-1229f94ec478)







5.	Wafello 
  

![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/696ec5ea-5d6a-4efd-8ae0-08b3a12ed3e1)



6.	Beng – beng
![Image](https://github.com/FaridBayu/Projek-akhir/assets/137608559/5f509232-d4ab-4ebc-a573-eb149fb98615)
