### ISSUE TITLE
desain kado

### ISSUE THREAD

**Issue by FaridBayu** [FaridBayu/Projek-akhir#11]
- berisi tentang warna/latar dari bungkus kado
- isi kado
- hiasan kado

**Comment by RizalMahardika** [comment]
Desain Awal :
![desain awal](https://github.com/FaridBayu/Projek-akhir/assets/155162342/f8cbe496-6092-48b1-96fd-ee8ec8e9f633)

Desain final :
![Desain final](https://github.com/FaridBayu/Projek-akhir/assets/155162342/fbc749dc-800e-4e67-85fb-64eb72b3e466)
