### ISSUE TITLE
pembuatan kado

### ISSUE THREAD

**Issue by FaridBayu** [FaridBayu/Projek-akhir#12]
- dokumentasi pembuatan kado

**Comment by RizalMahardika** [comment]
[CARA MEMBUAT KADO.pdf](https://github.com/FaridBayu/Projek-akhir/files/13938190/CARA.MEMBUAT.KADO.pdf)

**Comment by Kerfinaprian** [comment]
https://youtu.be/wI_eH7RQP4I?si=mHZdjhwscp8pa9m-
