### ISSUE TITLE
Pengiriman Produk

### ISSUE THREAD

**Issue by FaridBayu** [FaridBayu/Projek-akhir#16]
-bukti pengiriman

**Comment by Kerfinaprian** [comment]
Berikut bukti pengiriman yg diterima oleh Wafiqah


![Image](https://github.com/FaridBayu/Projek-akhir/assets/155155602/c4d1d6aa-595e-4320-ae71-4845441a26f2)
![Image](https://github.com/FaridBayu/Projek-akhir/assets/155155602/d7685218-c6b9-48c1-a053-b2d76c52aca0)
